backend:
  name: git-gateway
  branch: decap-cms # Branch to update (optional; defaults to master)
  commit_messages:
    create: 'docs: Create {{collection}} “{{slug}}”'
    update: 'docs: Update {{collection}} “{{slug}}”'
    delete: 'docs: Delete {{collection}} “{{slug}}”'
    uploadMedia: 'docs: Upload “{{path}}”'
    deleteMedia: 'docs: Delete “{{path}}”'
    openAuthoring: '{{message}}'

local_backend: true

publish_mode: editorial_workflow

media_folder: '.storybook/static/uploads'
public_folder: '/static/uploads'

collections:
  - name: 'docs' # Used in routes, e.g., /admin/collections/docs
    label: 'Docs' # Used in the UI
    folder: 'cms' # The path to the folder where the mdx documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    slug: '{{title}}' # Filename template, e.g., title.stories.mdx
    format: yaml-frontmatter
    frontmatter_delimiter: ['<!--', '-->']
    identifier_field: title
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
