export enum HEALTH_INDICATOR_STATUS {
  HEALTHY = 'healthy',
  WARNING = 'warning',
  AT_RISK = 'at-risk',
  CRITICAL = 'critical',
}

export const HEALTH_INDICATOR_DEFAULT_PERCENTAGE: Record<
  HEALTH_INDICATOR_STATUS,
  number
> = {
  [HEALTH_INDICATOR_STATUS.HEALTHY]: 100,
  [HEALTH_INDICATOR_STATUS.WARNING]: 72,
  [HEALTH_INDICATOR_STATUS.AT_RISK]: 46,
  [HEALTH_INDICATOR_STATUS.CRITICAL]: 26,
};

export const HEALTH_INDICATOR_STATUS_LABELS: Record<
  HEALTH_INDICATOR_STATUS,
  string
> = {
  [HEALTH_INDICATOR_STATUS.HEALTHY]: 'Healthy',
  [HEALTH_INDICATOR_STATUS.WARNING]: 'Warning',
  [HEALTH_INDICATOR_STATUS.AT_RISK]: 'At Risk',
  [HEALTH_INDICATOR_STATUS.CRITICAL]: 'Critical',
};
