import { addons } from 'storybook/manager-api';
import theme from './theme';

addons.setConfig({
  theme: theme,
  sidebar: {
    // Expand Generated by default; collapse others
    collapsedRoots: ['components', 'ai', 'global-components'],
  },
});
