name: 'Build'

on:
  pull_request:
  workflow_call:

env:
  GH_TOKEN: '${{ secrets.GH_TOKEN }}'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint
        run: npm run lint

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build component bundles
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist

  Build_Storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build storybook
        run: npm run build-storybook

      # - name: Upload build-storybook artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-storybook-artifact
      #     path: storybook-static

  Test:
    # needs: [Build_Storybook]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright
        run: npx playwright@latest install --with-deps

      # - name: Download build-storybook artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build-storybook-artifact
      #     path: storybook-static

      # - name: Serve Storybook and run tests
      #   run: |
      #     npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
      #       "npx http-server storybook-static --port 6006 --silent" \
      #       "npx wait-on tcp:6006 && npm run test"

      - name: Run tests
        run: npm run test
