name: 'Chromatic'
on:
  push:
    branches:
      - main
      - beta
  pull_request:
    types: [review_requested]
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: '(main|beta)'
          onlyChanged: true
          untraced: '**/custom-elements.json'
          zip: true
