name: 'Release'

on:
  push:
    branches:
      - main
      - beta
      - next
      - 'v[0-9]'

permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  GH_TOKEN: '${{ secrets.GH_TOKEN }}'

jobs:
  Build:
    uses: ./.github/workflows/build.yml

  Release:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          scope: '@kyndryl-design-system'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install semantic-release extra plugins
        run: npm i --save-dev @semantic-release/git --legacy-peer-deps

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN_PACKAGES }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: HUSKY=0 npx semantic-release
